language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

# Run linter, run tests, then create a build if everything passes
script:
  - npm run validate
  - npm run build

# Deployment to AWS S3
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAI67HTZTVPWXR7AMA
  secret_access_key:
    secure: klPhEB5JhfahYsVAG2tUoYsxKKQzWL9F91NixzBjHtzHwdQfLnflrkidtEQXZ61s/ez0bRwqR54TZF+SPpbvGxu1vQerFSlky6xBAIasoVy3wMkCLR6JShDUaQcgrPWzR6fvoRkMPNM3YSZVX/04eiQNx3XP2Fj+lKiudPUwEqAX3KWv4sN45Ehb/jE0GygbdrUAMle7Ynxrfw9y1kCzhrizhuXiF71+6H1x31seb5dK05pPDuHbh2EeAOpLEiu/zrffMm2bgf7uj6KXdeYrYYlUQrYoM/dSV2NZi+DT5X0Bc+dG+rHUH+K2pr+/zpyTSZv01duz8IkcqrRIhS1/oYT5P/SL5v8KWGen6bTk/zov1sl0G7bxUUWSSCHq8druXlkboVO47BfahkxX8RvxtSbKCklF0SJsDm8J1c1RNGCGK20JKU93xY/uTe4MQ2ITFrbQnIVrQzlYxnStXH4LDq0WLdXux9xFJhOj2hi3cs6OLTw7IMMIJe56Ya2GicG7SX6+dCiylvozba2UtnQROj7fYGrlVWDhgoV3xE058kFnpiTEIzf3CI4OTVl88ykMZUDA12cDLAGEOhIUuoHv8vmZrs/z9guCSYWnCRm6+cFU8dS5UaJDZ5HrevuAHPT4AKsQFnTp1U+uksCu/QR5ocF42zA890K+E0CIzt+Ha7w=
  bucket: rtfa-web
  local-dir: build
  on:
    branch: master
