export const ActionTypes = {
  /* Event Actions */
  LOAD_EVENTS: "LOAD_EVENTS",
  CREATE_NEW_EVENT: "CREATE_NEW_EVENT",
  SELECT_NEW_EVENT: "SELECT_NEW_EVENT",
  LOAD_TASKS_DATA: "LOAD_TASKS_DATA",

  /* Region Actions */
  CREATE_NEW_REGION: "CREATE_NEW_REGION",
  DELETE_REGION: "DELETE_REGION",
  TOGGLE_REGION_MARKER_BOX: "TOGGLE_REGION_MARKER_BOX",
  UPDATE_REGION: "UPDATE_REGION",

  /* HeatMap Actions */
  LOAD_HEATMAP_DATA: "LOAD_HEATMAP_DATA",
  LOAD_HISTORICAL_HEATMAP_DATA: "LOAD_HISTORICAL_HEATMAP_DATA",
  SET_HEATMAP_SLIDER_VALUE: "SET_HEATMAP_SLIDER_VALUE",
  TOGGLE_HEATMAP_HISTORICAL_MODE: "TOGGLE_HEATMAP_HISTORICAL_MODE",

  /* Emergency Notification Actions */
  LOAD_EMERGENCY_NOTIFICATIONS: "LOAD_EMERGENCY_NOTIFICATIONS",
  RESOLVE_EMERGENCY_NOTIFICATION: "RESOLVE_EMERGENCY_NOTIFICATION"
};
